# Generated by Django 4.1 on 2022-09-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='explanetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descubrimiento', models.CharField(max_length=100, verbose_name='descubrimiento')),
                ('masa', models.CharField(max_length=100, verbose_name='masa')),
                ('radio', models.CharField(max_length=100, verbose_name='radio')),
            ],
        ),
        migrations.CreateModel(
            name='userandpassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='correo')),
                ('nickname', models.CharField(max_length=100, verbose_name='nickname')),
            ],
        ),
    ]
