# Generated by Django 4.1 on 2022-10-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_userandpassword_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanetas',
            name='masa',
        ),
        migrations.RemoveField(
            model_name='explanetas',
            name='radio',
        ),
        migrations.AddField(
            model_name='explanetas',
            name='temperatura',
            field=models.CharField(default=1, max_length=100, verbose_name='Temperatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explanetas',
            name='tipo',
            field=models.CharField(default=1, max_length=100, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
