# Generated by Django 4.1 on 2022-10-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_remove_explanetas_temperatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanetas',
            name='distancia',
            field=models.CharField(default=1, max_length=100, verbose_name='Distancia'),
            preserve_default=False,
        ),
    ]
