# Generated by Django 4.1 on 2022-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_explanetas_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userandpassword',
            name='contrasena',
            field=models.CharField(default=1, max_length=100, verbose_name='Contrasena'),
            preserve_default=False,
        ),
    ]
